export const GAME_EVENTS = {
  CREATE_ROOM: 'CREATE_ROOM',
  JOIN_ROOM: 'JOIN_ROOM',
  REJOIN_ROOM: 'REJOIN_ROOM',
  START_GAME: 'START_GAME',
  SELECT_TOSS: 'SELECT_TOSS',
  SELECT_NUMBER: 'SELECT_NUMBER',
  SELECT_BOWLER: 'SELECT_BOWLER',
  ROUND_RESULT: 'ROUND_RESULT',
  SWITCH_INNINGS: 'SWITCH_INNINGS',
  GAME_STATE_UPDATE: 'GAME_STATE_UPDATE',
  GAME_OVER: 'GAME_OVER',
  REMATCH_REQUEST: 'REMATCH_REQUEST',
  TEAM_SWAP: 'TEAM_SWAP',
  PLAYER_DISCONNECTED: 'PLAYER_DISCONNECTED',
  PLAYER_RECONNECTED: 'PLAYER_RECONNECTED',
  RENAME_TEAM: 'RENAME_TEAM',
  ERROR: 'ERROR',
} as const;

export type GameEventName = (typeof GAME_EVENTS)[keyof typeof GAME_EVENTS];
