export const GAME_CONSTANTS = {
  MIN_PLAYER_NAME_LENGTH: 1,
  MAX_PLAYER_NAME_LENGTH: 24,
  MIN_TEAM_NAME_LENGTH: 1,
  MAX_TEAM_NAME_LENGTH: 24,
  MIN_ROOM_ID_LENGTH: 4,
  MAX_ROOM_ID_LENGTH: 8,
  MIN_TEAM_SIZE: 1,
  MAX_TEAM_SIZE: 5,
  DEFAULT_TEAM_SIZE: 2,
  MIN_SELECT_NUMBER: 1,
  MAX_SELECT_NUMBER: 6,
  BALLS_PER_OVER: 6,
  WICKETS_PER_INNINGS: 10,
  ERROR_DISPLAY_DURATION_MS: 5000,
  SOCKET_TIMEOUT_MS: 15000,
  RATE_LIMIT_WINDOW_MS: 5000,
  RATE_LIMIT_MAX: 10,
  ROOM_EXPIRY_MS: {
    WAITING: 24 * 60 * 60 * 1000,
    ACTIVE: 60 * 60 * 1000,
    COMPLETED: 60 * 60 * 1000,
  },
} as const;

export const WEBSOCKET_CONFIG = {
  PING_TIMEOUT: 60000,
  PING_INTERVAL: 25000,
} as const;